$primary = rgb(8000ff)
$secondary = rgb(00eaff)

$accent = rgb(1788e4)
$surface = rgb(11111B)
$text = rgb(ffffff)
$danger = rgb(e06c75)
$success = rgb(98c379)
$warning = rgb(e5c07b)
$info = rgb(61afef)
$muted = rgb(929db1)
