# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

# See https://wiki.hyprland.org/Configuring/Window-Rules/

# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules2

# windowrule = suppressevent maximize, class:.* # You'll probably like this.

windowrule = workspace special:magic, match:class whatsdesk
windowrule = workspace special:magic, match:class discord

windowrule = opacity 1.0 0.9, match:class kitty
windowrule = opacity 0.90 0.85, match:class thunar
windowrule = no_blur on, match:class thunar

windowrule = opacity 0.96 0.90, match:class firefox


windowrule = opacity 0.9 0.9, match:class Spotify
# No aplicar blur ventana de Xdg-desktop-portal-gtk
# windowrulev2 = noblur, class:^(Xdg-desktop-portal-gtk)$

windowrule = no_blur on, match:class Xdg-desktop-portal-gtk

windowrule = no_blur on, match:class swaync-notification-window
windowrule = no_blur on, match:class swaync


# █░░ ▄▀█ █▄█ █▀▀ █▀█   █▀█ █░█ █░░ █▀▀ █▀
# █▄▄ █▀█ ░█░ ██▄ █▀▄   █▀▄ █▄█ █▄▄ ██▄ ▄█


# blurls = rofi
# blurls = notifications  
# blurls = swaync-notification-window
# blurls = swaync-control-center
#
layerrule = blur on, match:namespace swaync-control-center

layerrule = blur off, match:namespace swaync-notification-window
layerrule = ignore_alpha 0.1, match:namespace swaync-notification-window

layerrule = blur on, match:class rofi
layerrule = blur on, match:class logout_dialog
# layerrule = ignorezero,rofi
# layerrule = blur,notifications
# layerrule = ignorezero,notifications
# layerrule = blur,swaync-notification-window
# layerrule = ignorezero,swaync-notification-window
# layerrule = blur,swaync-control-center
# layerrule = ignorezero,swaync-control-center
# layerrule = blur,logout_dialog
